name: zam_command_pattern
version: 0.2.0
description: Provides utilities to implement the command pattern (a behavioral
  design pattern).
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_command_pattern

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  zam_core: ^0.6.0
  zam_factory_pattern: ^0.2.0

dev_dependencies:
  lints: ^1.0.1
  zam_test: ^0.4.0
